version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    image: node:14
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run start:dev"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: test
      DB_PASSWORD: test
      DB_NAME: test
    depends_on:
      - db

volumes:
  db-data: